#!/usr/bin/env python3
"""Generate TDM/I2S example waveforms and matching .sucl command files.

Run from the repository root:
    python3 examples/generate_tdm_examples.py
"""

import math
import os

FRAMES = 3


def sample_values(bits, channels, frames):
    magnitude = 1 << (bits - 1)
    amplitude = magnitude - 1
    return [
        [
            int(amplitude * math.sin(2 * math.pi * (frame / frames + channel / channels)))
            for channel in range(channels)
        ]
        for frame in range(frames)
    ]


def sample_bit(sample, bits, index):
    raw = sample & ((1 << bits) - 1)
    return (raw >> (bits - 1 - index)) & 1


def pulse_edge_bit(justification, bits, channels, slot_width, offset, frame, edge):
    if edge < offset:
        return 0
    x = edge - offset
    slot = x // slot_width
    position = x % slot_width
    if slot >= channels:
        return 0
    if justification == "left":
        if position >= bits:
            return 0
        return sample_bit(frame[slot], bits, position)
    if position < slot_width - bits:
        return 0
    return sample_bit(frame[slot], bits, position - (slot_width - bits))


def slot_edge_bit(justification, bits, slot_width, offset, sample, edge):
    if edge < offset:
        return 0
    position = edge - offset
    if justification == "left":
        if position >= bits:
            return 0
        return sample_bit(sample, bits, position)
    if position < slot_width - bits:
        return 0
    return sample_bit(sample, bits, position - (slot_width - bits))


def build_events(mode, justification, bits, channels, slot_width, offset, active_high,
                 bitclk_rising=True, frame_sync_rising=True):
    start_parity = 0 if bitclk_rising else 1
    fs_active = 1 if frame_sync_rising else 0
    samples = sample_values(bits, channels, FRAMES)
    events = []

    if mode == "pulse":
        frame_width = offset + channels * slot_width
        frame_duration = 2 * frame_width + 2
        for frame_index, frame in enumerate(samples):
            frame_start = start_parity + frame_index * frame_duration
            data = 0
            for phase in range(frame_duration):
                time = frame_start + phase
                clk = time % 2
                fs = fs_active if phase < 2 else 1 - fs_active
                if phase % 2 == 1:
                    edge = (phase - 1) // 2
                    if edge < frame_width:
                        data = pulse_edge_bit(
                            justification, bits, channels, slot_width, offset, frame, edge
                        )
                events.append((time, clk, fs, data))
    else:
        # A right-justified sample occupies the end of its (offset-shifted)
        # slot window, so the slot has `offset` extra clock edges.
        slot_edges = offset + slot_width if justification == "right" else slot_width
        slot_duration = 2 * slot_edges + 2
        frame_duration = channels * slot_duration
        for frame_index, frame in enumerate(samples):
            frame_start = start_parity + frame_index * frame_duration
            for channel in range(channels):
                slot_start = frame_start + channel * slot_duration
                fs = 1 if (channel == 0) == active_high else 0
                data = 0
                for phase in range(slot_duration):
                    time = slot_start + phase
                    clk = time % 2
                    if phase % 2 == 1:
                        edge = (phase - 1) // 2
                        if edge < slot_edges:
                            data = slot_edge_bit(
                                justification, bits, slot_width, offset, frame[channel], edge
                            )
                    events.append((time, clk, fs, data))

    return events


def write_vcd(path, events):
    lines = [
        "$timescale 1ns $end",
        "$scope module tb $end",
        "$var wire 1 a bitclk $end",
        "$var wire 1 b frame_sync $end",
        "$var wire 1 c data $end",
        "$upscope $end",
        "$enddefinitions $end",
    ]
    last = (None, None, None)
    for time, clk, fs, data in events:
        values = (clk, fs, data)
        if values == last:
            continue
        lines.append(f"#{time}")
        if clk != last[0]:
            lines.append(f"{clk}a")
        if fs != last[1]:
            lines.append(f"{fs}b")
        if data != last[2]:
            lines.append(f"{data}c")
        last = values
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")


def write_sucl(path, settings):
    lines = [
        "# Auto-generated by examples/generate_tdm_examples.py",
        "variable_add tb.bitclk",
        "variable_add tb.frame_sync",
        "variable_add tb.data",
        f"decoder_add tdm_audio tb.bitclk tb.frame_sync tb.data {settings}",
    ]
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")


def main():
    here = os.path.dirname(os.path.abspath(__file__))

    examples = [
        (
            "tdm_audio_left_8ch_24bit",
            dict(mode="pulse", justification="left", bits=24, channels=8,
                 slot_width=32, offset=0, active_high=True),
            "channels=8 bits=24 slot_width=32 justification=left",
        ),
        (
            "tdm_audio_right_8ch_24bit",
            dict(mode="pulse", justification="right", bits=24, channels=8,
                 slot_width=32, offset=0, active_high=True),
            "channels=8 bits=24 slot_width=32 justification=right",
        ),
        (
            "i2s_audio_2ch_24bit",
            dict(mode="level", justification="left", bits=24, channels=2,
                 slot_width=32, offset=1, active_high=False),
            "mode=level active_high=false offset=1 channels=2 bits=24 slot_width=32",
        ),
        (
            "tdm_audio_left_8ch_24bit_falling_bitclk",
            dict(mode="pulse", justification="left", bits=24, channels=8,
                 slot_width=32, offset=0, active_high=True, bitclk_rising=False),
            "channels=8 bits=24 slot_width=32 justification=left edge=falling",
        ),
        (
            "tdm_audio_left_8ch_24bit_falling_fs",
            dict(mode="pulse", justification="left", bits=24, channels=8,
                 slot_width=32, offset=0, active_high=True, frame_sync_rising=False),
            "channels=8 bits=24 slot_width=32 justification=left fs_edge=falling",
        ),
        (
            "tdm_audio_left_8ch_24bit_falling_both",
            dict(mode="pulse", justification="left", bits=24, channels=8,
                 slot_width=32, offset=0, active_high=True,
                 bitclk_rising=False, frame_sync_rising=False),
            "channels=8 bits=24 slot_width=32 justification=left edge=falling fs_edge=falling",
        ),
        (
            "tdm_audio_right_8ch_24bit_falling_both",
            dict(mode="pulse", justification="right", bits=24, channels=8,
                 slot_width=32, offset=0, active_high=True,
                 bitclk_rising=False, frame_sync_rising=False),
            "channels=8 bits=24 slot_width=32 justification=right edge=falling fs_edge=falling",
        ),
    ]

    for name, spec, settings in examples:
        vcd_path = os.path.join(here, f"{name}.vcd")
        sucl_path = os.path.join(here, f"{name}.sucl")
        write_vcd(vcd_path, build_events(**spec))
        write_sucl(sucl_path, settings)
        print(f"wrote {vcd_path} and {sucl_path}")


if __name__ == "__main__":
    main()
