#!/usr/bin/env python3
"""Generate S/PDIF / AES3 example waveforms and matching .sucl files.

Run from the repository root:
    python3 examples/generate_spdif_examples.py
"""

import math
import os

# Preamble patterns (EBU Tech 3250 §2.4); the complement is used when the
# preceding line state is 1.
PREAMBLES = {
    "X": [1, 1, 1, 0, 0, 0, 1, 0],
    "Y": [1, 1, 1, 0, 0, 1, 0, 0],
    "Z": [1, 1, 1, 0, 1, 0, 0, 0],
}

FRAMES = 192  # one channel-status block
HALF_PERIOD = 4


def append_preamble(half, preamble, level):
    pattern = PREAMBLES[preamble]
    chosen = [1 - bit for bit in pattern] if level == pattern[0] else pattern
    half.extend(chosen)
    return chosen[-1]


def append_bits(half, bits, level):
    for bit in bits:
        level = 1 - level  # boundary transition
        half.append(level)
        if bit:
            level = 1 - level  # mid-cell transition
        half.append(level)
    return level


def subframe_bits(sample, word_bits, validity, user, channel_status):
    bits = [0] * 28
    # MSB is slot 27; the LSB moves down as the word gets shorter.
    first = 24 - word_bits
    raw = sample & ((1 << word_bits) - 1)
    for offset in range(word_bits):
        bits[first + offset] = (raw >> offset) & 1  # MSB at slot 27
    bits[24] = validity
    bits[25] = user
    bits[26] = channel_status
    bits[27] = sum(bits[:27]) % 2  # even parity over slots 4-31
    return bits


def consumer_status(sample_rate_code, word_length_code, max_24):
    """Consumer channel status (IEC 60958-3)."""
    status = [0] * 24
    status[0] = 0x00  # consumer, linear PCM
    status[1] = 0x00  # category: general
    status[2] = 0x00  # source 0, channel 0
    status[3] = sample_rate_code
    status[4] = (word_length_code << 1) | int(max_24)
    return status


def status_bit(status, frame):
    return (status[frame // 8] >> (frame % 8)) & 1


def build_half_cells(word_bits, status, sample):
    half = []
    level = 0
    for frame in range(FRAMES):
        left, right = sample(frame)
        preamble_a = "Z" if frame == 0 else "X"
        level = append_preamble(half, preamble_a, level)
        level = append_bits(
            half,
            subframe_bits(left, word_bits, 0, 0, status_bit(status, frame)),
            level,
        )
        level = append_preamble(half, "Y", level)
        level = append_bits(
            half,
            subframe_bits(right, word_bits, 0, 0, status_bit(status, frame)),
            level,
        )
    # Terminating transition so the final half-cell group is complete.
    level = 1 - level
    half.append(level)
    return half


def sine_cosine(amplitude, period):
    def sample(frame):
        angle = 2 * math.pi * frame / period
        return (
            int(amplitude * math.sin(angle)),
            int(amplitude * math.cos(angle)),
        )

    return sample


def write_vcd(path, half_cells):
    lines = [
        "$timescale 1ns $end",
        "$scope module tb $end",
        "$var wire 1 c data $end",
        "$upscope $end",
        "$enddefinitions $end",
    ]
    last = None
    for index, level in enumerate(half_cells):
        if level != last:
            lines.append(f"#{index * HALF_PERIOD}")
            lines.append(f"{level}c")
            last = level
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")


def write_sucl(path):
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(
            "\n".join(
                [
                    "# Auto-generated by examples/generate_spdif_examples.py",
                    "variable_add tb.data",
                    "decoder_add spdif tb.data analog=interpolated",
                    "",
                ]
            )
        )


def write_example(here, stem, word_bits, status, sample):
    vcd_path = os.path.join(here, f"{stem}.vcd")
    sucl_path = os.path.join(here, f"{stem}.sucl")
    write_vcd(vcd_path, build_half_cells(word_bits, status, sample))
    write_sucl(sucl_path)
    print(f"wrote {vcd_path} and {sucl_path}")


def main():
    here = os.path.dirname(os.path.abspath(__file__))

    # 48 kHz, 24-bit stereo: full-scale sine/cosine with a 16-frame period.
    write_example(
        here,
        "spdif_2ch_24bit",
        word_bits=24,
        status=consumer_status(0x02, 5, True),
        sample=sine_cosine(2**23 - 1, 16),
    )


if __name__ == "__main__":
    main()
